name: atsa
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_auth: ^1.1.3
  fluttertoast: ^8.0.6
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/img/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/img/
